### ISSUE TITLE
how to use gdal_polygonize

### ISSUE THREAD

**Issue by kongdd** [JuliaGeo/GDAL.jl#104]
Dear developers,

Could you give an example about how to use `gdal_polygonize`?

Cheers,
Dongdong

**Comment by visr** [comment]
I don't have an example sorry. Perhaps if you share what you tried as a small runnable example, people can give suggestions.

Which polygonize do you mean? If it is the `gdal_polygonize.py` Python command line tool, that is not provided with the binary, since we would have to include Python itself. But there is also the `GDALPolygonize` function, described here:

https://gdal.org/api/gdal_alg.html#_CPPv414GDALPolygonize15GDALRasterBandH15GDALRasterBandH9OGRLayerHiPPc16GDALProgressFuncPv

Which is wrapped here:
https://github.com/JuliaGeo/GDAL.jl/blob/4a7a9171c64469279e49cc72873f35c67f39c057/src/gdal_alg.jl#L131-L157

This function is not in the tests currently, but perhaps you can use the existing tests to try to produce an example.

**Comment by kongdd** [comment]
Thanks for your quick response. I will have a try.

**Comment by kongdd** [comment]
Thank you. Solved

**Comment by visr** [comment]
Glad you solved it. Would be nice if you could post an example here in case anyone else has the same issue.

**Comment by kongdd** [comment]
It is at here, https://github.com/geo-julia/GeoArrays.jl/blob/master/src/gdal_polygonize.jl#L3.
