### ISSUE TITLE
getattrvalue can be avoid throw expection and more julia way

### ISSUE THREAD

**Issue by huaxk** [JuliaGeo/GDAL.jl#67]
`function getattrvalue(hSRS::Ref{OGRSpatialReferenceH}, pszName, iChild::Integer) `

return unsafe_string directly, if the result ccall returned is NULL, unsafe_string throw exception:

`ERROR: ArgumentError: cannot convert NULL to string`

call getattrvalue function need to handle exception,not easy to use.

I think getattrvalue function can add a judgment when returning, avoid to throw exception:
```
function getattrvalue(hSRS::Ref{OGRSpatialReferenceH}, pszName, iChild::Integer)
    result = ccall((:OSRGetAttrValue, libgdal), Cstring, (Ptr{Cvoid}, Cstring, Cint), hSRS, pszName, iChild)
    result != Cstring(Ptr{UInt8}(0)) ? unsafe_string(result) : nothing
end
```
I can call getattrvalue function by this way:
```
if getattrvalue(...) != nothing
...
else
...
end
```
or
`getattrvalue(...) != nothing && ...`

Instead of handling exceptions, do you think so ?

**Comment by visr** [comment]
Hmm, yes the current error is not very clear. Do you know if GDAL reports an error here? In general we use this function:
https://github.com/JuliaGeo/GDAL.jl/blob/0376a7ed0ab711b499a795045858e50081c28d79/src/error.jl#L31-L37

And only throw on CE_Failure and CE_Fatal error conditions reported by GDAL. If that is the case here, we should just wrap it in `failsafe`. Could you check this? Or provide a simple minimum working example such that we can check together.

If we decide to go for returning `nothing`, maybe that should be done for all here:
https://github.com/JuliaGeo/GDAL.jl/blob/0376a7ed0ab711b499a795045858e50081c28d79/gen/rewriter.jl#L171-L172
I prefer general solutions rather than making exceptions on a case by case (function by function) basis.
