### ISSUE TITLE
Can not build on Julia 1.2 - Windows 10

### ISSUE THREAD

**Issue by DrJonBall** [JuliaGeo/GDAL.jl#80]
I get the following error:
> ERROR: Can not create symbolic link : A required privilege is not held by the client.

This looks like a similar issue to [this one](https://github.com/JuliaIO/ImageMagick.jl/issues/133) in another package.

The problem would appear to be that in Windows, there is no way of creating symlinks without admin privileges.  The work-around of switching to Developer Mode also requires elevated privileges.

A "dirty hack" (their words, not mine) is offered towards the end of the linked issue.

**Comment by visr** [comment]
Hmm unfortunate that this still doesn't work. I noticed in https://github.com/JuliaPackaging/BinaryProvider.jl/releases/tag/v0.5.5 that it is fixed in BinaryProvider v0.5.5, but this release was yanked from the registry because it had issues, so v0.5.6 is v0.5.4, which does not include the fix.

They are aware of the issues, see https://github.com/JuliaPackaging/BinaryProvider.jl/issues/172#issuecomment-531044851.

I don't think there is much I can do in this repository.

Have you tried setting the environment variable `BINARYPROVIDER_COPYDEREF=true`, does that work for you?

**Comment by visr** [comment]
Ok this should no longer be a problem in GDAL.jl 1.0.2 due to the new build used in #81.

I checked if there are any symbolic links present still, and there are none. If it still doesn't work without administrator rights, please let us know and reopen the issue! Thanks!

**Comment by jkwwwwow** [comment]
Hi @visr
I am a beginner, I wonder how to implement the operation you mentioned that "setting the environment variable BINARYPROVIDER_COPYDEREF=true"? 
What's the command should I type in ubuntu terminal?

**Comment by visr** [comment]
Hi @jkwwwwow. Do you get the same error as posted above, `ERROR: Can not create symbolic link`? Which julia version are you using?

If you are on a recent julia, 1.3 or higher, and GDAL.jl 1.1 or higher, you don't have to set any evironment variables, and everything should just work.

But for your information, you can set environment variables for the duration of your session with this syntax: `export VARNAME="my value"`.
