### ISSUE TITLE
Specific file listed in errors?

### ISSUE THREAD

**Issue by rafaqz** [JuliaGeo/GDAL.jl#96]
It would be nice if an error like this reported the file name in question:

```julia
ERROR: GDALError (CE_Failure, code 3):
        File short, can't read line 204.
```

Especially when looping over large datasets with hundreds of files. I'm not sure how easy that is to do or where to do it exactly - this could be something for ArchGDAL.jl

**Comment by visr** [comment]
Yeah it's unfortunate that the file name is not mentioned here.

In this package we hook onto the error handler of GDAL, using the API GDAL provides for that.

The source code for that is here: https://github.com/JuliaGeo/GDAL.jl/blob/79560db2e494dd41c800df30ee8ab26384360a5c/src/error.jl
And we hook this in during module load: https://github.com/JuliaGeo/GDAL.jl/blob/79560db2e494dd41c800df30ee8ab26384360a5c/src/GDAL.jl#L36-L38

So the message that you are seeing is not coming from this package, but from GDAL itself. So the best location to improve this would be in GDAL, you could submit an issue here: https://github.com/OSGeo/gdal. ArchGDAL is using the same error handling. I think it would make it unneccesarily complicated if we were to try to augment some of the error messages that we deem not good enough. This error is thrown because GDAL decides it wants to throw an error. That gets caught in our error callback.

**Comment by rafaqz** [comment]
Sure I get that `GDALerror` works like that. But at some point in the chain someone should improve the errors. I'll try gdal directly and see how it goes.

**Comment by visr** [comment]
Looks like this comes from https://github.com/OSGeo/gdal/blob/20d44a181f73b87ebb7c1660498bb9e78e572e54/gdal/frmts/aaigrid/aaigriddataset.cpp#L187, so the AAIGrid driver. We're using a somewhat older GDAL version at the moment, 3.0.4, but it's the same in GDAL master.

Grepping `CPLError(CE_Failure, CPLE_FileIO` it seems most IO errors don't report the file name, except for instance: `CPLError(CE_Failure, CPLE_FileIO, "Cannot create %s", pszFilename);`.

**Comment by rafaqz** [comment]
They literally fixed it already: https://github.com/OSGeo/gdal/pull/3054

**Comment by visr** [comment]
Gotta love Even's dedication :)
